#!/bin/bash
# Author: Mauro Ianni
# Description: ....................

# 22/09/2015 - First writing

# no parameters expected

# script name
ScNm="$(echo $0|sed "s/.*\///")"

# set output file name (with day)
ofn="./log_files/${ScNm}_$(date +%Y%m%d).log"


RD_list="1 2 3 7 15 23 31"
SZ_list="4096 8192 16384 32768 65536 131072"
LD_list="0 1"

cd registerHPDCS
make clean
make
cd ..

echo "starting test on registerHPDCS"

for LD in $LD_list
do
	for SZ in $SZ_list
	do 
		for RD in $RD_list
		do 
			./registerHPDCS/test 1 $RD $SZ 0 0 10 $LD>> ./results/HPDCS_LD=${LD}.dat
  		done
	done
done

cd registerLarsson
make clean
make
cd ..

echo "starting test on registerLarsson"

for LD in $LD_list
do
	for SZ in $SZ_list
	do 
		for RD in $RD_list
		do 
			./registerLarsson/test 1 $RD $SZ 0 0 10 $LD>> ./results/LARSSON_LD=${LD}.dat
  		done
	done
done

cd registerPeterson
make clean
make
cd ..

echo "starting test on registerPeterson"

for LD in $LD_list
do
	for SZ in $SZ_list
	do 
		for RD in $RD_list
		do 
			./registerPeterson/test 1 $RD $SZ 0 0 10 $LD>> ./results/PETERSON_LD=${LD}.dat
  		done
	done
done

cd registerLock
make clean
make
cd ..

echo "starting test on registerLock"

for LD in $LD_list
do
	for SZ in $SZ_list
	do 
		for RD in $RD_list
		do 
			./registerLock/test 1 $RD $SZ 0 0 10 $LD>> ./results/LOCK_LD=${LD}.dat
  		done
	done
done

